http:
  listener:
    host: "localhost"
    port: "9091"
    path: "/travelOnTipcall/{serviceType}"
  sql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "Sowmya@123"
    database: "dummy"
      